title: Add training data to your ML model
hero_image: images/banner.png
description: Add training data to your ML model in ML4K
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add training data to your ML model